package-lock.json, package.json, tsconfig.json
Bumped up dependencies of loopback packages
=> bumped up dependencies

.eslintignore, src/providers/ratelimit-action.provider.ts
Ran `npm run lint:fix`
Changes to lint config
=> lint fixes and lint config fixes

package-lock.json, package.json
Updated `loopback-connector-kv-redis` version
=> updated loopback redis connector version

package-lock.json, package.json
Description
Updated versions of All Loopback packages.
Type of change
=> fix(version): updated version of all loopback packages

.cz-config.js, .eslintignore, .github/PULL_REQUEST_TEMPLATE.md, .husky/commit-msg, .husky/pre-commit, .husky/prepare-commit-msg, DEVELOPING.md, commitlint.config.js, package-lock.json, package.json, src/providers/ratelimit-datasource.provider.ts, src/types.ts
Added husky hooks for commitizen, commit linting, and pre-commit tests.
=> feat(ci-cd): add commitizen, commitlint, pre-commit tests

README.md, src/providers/ratelimit-datasource.provider.ts
Fix datasource passing issue in the provider.
Fixes #25
=> fix(datasources): fix datasource passing bug in the provider

package.json, src/providers/ratelimit-datasource.provider.ts
Fixed store type, added a missing dev dependency.
=> fix(providers): fix store typings

src/providers/ratelimit-action.provider.ts, src/providers/ratelimit-datasource.provider.ts
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (#19 )
=> fix(providers): windowMs property was not working inside decorator

package-lock.json, package.json
=> chore(deps): update semantic release

package.json
No need of semantic changelog as we are generating our custom
GH-87
No need of semantic changelog as we are generating our custom
Fixes #87 
=> fix(chore): remove semantic changelog library

.sonarcloud.properties
sonar properties to be run on PR and master
GH-103
sonar properties to be run on PR and master
Fixes #103 
=> chore(ci-cd): added the missing sonar properties

src/providers/ratelimit-datasource.provider.ts, src/types.ts
- Resolving sonar smells to improve quality gate
GH-94
Fixes #94
=> fix(chore): fix sonar code smells

README.md
Add description for applying Ratelimit on OBF.
GH-120
Add description for applying Ratelimit on OBF.
Fixes #120 
=> docs(middleware): add description for applying ratelimit on OBF

.github/workflows/release.yaml
release will be via the worklow
GH-136
add github release workflow
Fixes #136 
=> chore(ci-cd): add github release workflow

.prettierrc, src/__tests__/acceptance/in-memory-store.ts, src/__tests__/acceptance/ratelimit-action-acceptance/rate-limiter.acceptance.ts, src/__tests__/acceptance/store.provider.ts, src/__tests__/acceptance/test.controller.ts, src/__tests__/unit/ratelimit-action.provider.unit.ts, src/__tests__/unit/ratelimit-datasource.provider.unit.ts, src/providers/ratelimit-datasource.provider.ts, src/release_notes/post-processing.js, src/release_notes/release-notes.js, src/types.ts
fix sonar code smells related to magic numbers and cognitive complexity
GH-148
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #148 
=> refactor(chore): fix sonar code smells

docs/README.md, package-lock.json
fix vulnerabilites as well
GH-147
add sonar synk badges
Fixes #147 
=> docs(chore): add sonar synk badges

package.json
dummy commit for previous wrong commit message for @loopback version updates
GH-153
dummy commit for wrong commit message for the dependencies and devDependencies 
version upgrade
Fixes # (issue)
=> chore(deps): dummy commit for version update

.github/workflows/sync-docs.yaml, package-lock.json
change the read me path in sync docs action
GH-156
update the readme path in sync docs action
Fixes #156 
=> chore(ci-cd): update the readme path in sync docs action

.github/workflows/main.yaml, .github/workflows/release.yaml, package-lock.json, package.json
add the missing ci check on prs
GH-172
step to generate changelog
add the missing ci check on prs
Fixes #172 
=> fix(ci-cd): step to generate changelog

package-lock.json, src/middleware/ratelimit.middleware.ts
fix promise initialisation
GH-181
Fix promise initialisation in ratelimit middleware.
Fixes #181 
=> fix(middleware): fix promise initialisation

src/middleware/ratelimit.middleware.ts, src/providers/ratelimit-action.provider.ts
=> fix promise initialisation

package-lock.json, package.json
node version update
Fixes # (issue)
=> chore(deps): node version update
